### ISSUE TITLE
xyz calc details

### ISSUE THREAD

**Issue by iynehz** [drzowie/PDL-Transform-Color#8]
While looking at the other issue I raised about t_lab, I found some xyz calc details not same as what's on Wikipedia:

The sRGB <=> linear thresolds are different from what's in the code now:
https://en.wikipedia.org/wiki/SRGB#From_sRGB_to_CIE_XYZ thresold value 0.04045, as opposed to 0.03928 in code 
https://github.com/PDLPorters/PDL-Transform-Color/blob/efb667774ad7b676f282382dca7014f3726e4330/lib/PDL/Transform/Color.pm#L636

https://en.wikipedia.org/wiki/SRGB#From_CIE_XYZ_to_sRGB thresold value 0.0031308, as opposed to 0.00304 in code
https://github.com/PDLPorters/PDL-Transform-Color/blob/efb667774ad7b676f282382dca7014f3726e4330/lib/PDL/Transform/Color.pm#L620

Also, the conversion matrix is slightly different: see https://en.wikipedia.org/wiki/SRGB#sYCC vs 
https://github.com/PDLPorters/PDL-Transform-Color/blob/efb667774ad7b676f282382dca7014f3726e4330/lib/PDL/Transform/Color.pm#L371-L373

And there was some discussion on discrepancy of sources and people's conclusion was that the old values like 0.00304 incorrect. https://en.wikipedia.org/wiki/Talk%3ASRGB#Discrepancy_between_sources 

I understand the differences could be trivial and maybe even not observable on integer 0-255. But I wonder if you should change to follow the correct standard.

**Comment by mohawk2** [comment]
I want the code here to be as correct as possible. I'd be very interested if you could look at the code in https://github.com/PDLPorters/PDL-Graphics-ColorSpace/blob/master/color_space.c and see if that looks to you like it conforms?

**Comment by iynehz** [comment]
Yes that one's rgb2xyz and xyz2rgb look good to me.

**Comment by mohawk2** [comment]
I've extracted the code in those two into `rgb_from_linear` and `rgb_to_linear`, and am using that in this module locally. As soon as the newly-uploaded version is available on CPAN, I'll be finishing up changing this one to mainly use PDL::Graphics::ColorSpace.

**Comment by mohawk2** [comment]
I have now uploaded a new 1.007. Please try it out and report problems. If instead it actually works, please close the issue!

**Comment by mohawk2** [comment]
I see https://github.com/stphnlyd/perl5-Chart-GGPlot/issues/12 is now closed - does that mean this issue can be as well?

**Comment by mohawk2** [comment]
Closing as I believe this is fully resolved. Please comment/reopen if not!

**Comment by mohawk2** [comment]
Closing as I believe this is fully resolved. Please comment/reopen if not!
